### ISSUE TITLE
npm registry for w3c

### ISSUE THREAD

**Issue by bkelley13** [octref/svg-sample#2]
What's the npm registry setting for the svg line in the package dependencies?  I'd like to npm install and vsce build this, but I see npm install error for w3c/svgwg stuff, I think I need the registry setting for w3c?

Second, the settings.json contributes experimental html data line doesn't seem to work for me in my local tests?  I set it to relative or absolute paths, no difference, the setting isn't getting picked up.  I can only get it to work out of a workspace settings.json?  is it working for others?

**Comment by octref** [comment]
I was pulling it from GitHub since it's not a NPM module: https://github.com/w3c/svgwg.
